"'Settings Screen' As screen":
    Fill: =RGBA(237, 237, 237, 1)

    cmp_Settings_Title As cmp_SideNav:
        Items: =colSidebarItems
        Default: ="Vehicles"
        Y: =60
        Height: =708

    lbl_Settings_Title As label:
        Text: =App.ActiveScreen.Name
        Font: =Font.'Segoe UI'
        Align: =Center
        Size: =20
        ZIndex: =1
        Height: =60
        Width: =App.Width
        FontWeight: =Normal
        Fill: =RGBA(39, 67, 125, 1)
        Color: =RGBA(255, 255, 255, 1)

    con_Settings_Main As groupContainer:
        ZIndex: =5
        LayoutOverflowY: =LayoutOverflow.Hide
        LayoutOverflowX: =LayoutOverflow.Hide
        LayoutJustifyContent: =LayoutJustifyContent.Start
        LayoutAlignItems: =LayoutAlignItems.Start
        LayoutDirection: =LayoutDirection.Horizontal
        LayoutMode: =LayoutMode.Manual
        DisplayMode: =DisplayMode.Edit
        Height: =708
        Width: =1286
        Y: =60
        X: =80
        Fill: =RGBA(0, 0, 0, 0)
        BorderStyle: =BorderStyle.Solid
        BorderColor: =RGBA(0, 0, 0, 1)

        tog_Settings_1 As toggleSwitch:
            Size: =20
            Y: =76
            X: =364
            ZIndex: =1
            Width: =118
            Font: =Font.'Segoe UI'
            Height: =36

        tog_Settings_3 As toggleSwitch:
            Size: =20
            Y: =76
            X: =758
            ZIndex: =2
            Width: =118
            Font: =Font.'Segoe UI'
            Height: =36

        tog_Settings_2 As toggleSwitch:
            Size: =20
            Y: =178
            X: =364
            ZIndex: =3
            Width: =118
            Font: =Font.'Segoe UI'
            Height: =36

        tog_Settings_4 As toggleSwitch:
            Size: =20
            Y: =178
            X: =758
            ZIndex: =4
            Width: =118
            Font: =Font.'Segoe UI'
            Height: =36

        lbl_Settings_1 As label:
            Text: ="Setting 1"
            Size: =20
            ZIndex: =5
            Y: =76
            X: =143
            Font: =Font.'Segoe UI'

        lbl_Settings_2 As label:
            Text: ="Setting 2"
            Size: =20
            ZIndex: =6
            Y: =174
            X: =143
            Font: =Font.'Segoe UI'

        lbl_Settings_3 As label:
            Text: ="Setting 3"
            Size: =20
            ZIndex: =7
            Y: =72
            X: =575
            Font: =Font.'Segoe UI'

        lbl_Settings_4 As label:
            Text: ="Setting 4"
            Size: =20
            ZIndex: =8
            Y: =174
            X: =575
            Font: =Font.'Segoe UI'

